batch_size: 1
beta1: 0.5
beta2: 0.999
dataset_name: Kligler
height: 512
lambda1: 1.0
lambda2: 0.01
learning_rate: 0.003
loss_function_name: L1
max_epoch: 300
model: benet
num_workers: 8
pretrained: false
width: 512
